name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install test dependencies
        run: |
          Rscript -e 'install.packages(c("testthat"), repos="https://cloud.r-project.org")'
          # If your tests use dplyr, ggplot2, etc., add them here:
          # Rscript -e 'install.packages(c("dplyr","ggplot2"), repos="https://cloud.r-project.org")'

      - name: Run tests
        run: |
          Rscript -e 'library(testthat); test_dir("tests")'

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/_results

      - name: Clean up
        run: echo "Done!"