name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("devtools", "testthat"), repos="https://cloud.r-project.org")'
          Rscript -e 'devtools::install_deps(dependencies = TRUE)'

      - name: Run tests
        run: |
          Rscript -e 'library(testthat); test_dir("tests")'

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/_results

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Clean up
        run: echo "Done!"